name: CMake

on:
  # Trigger the workflow on push or pull request - but only for the main branch
  push:
    branches:
      - master
    tags-ignore:
      - 'v*'
  pull_request:
    branches:
      - master

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-on-windows:
    runs-on: windows-2022

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
        submodules:  recursive

    - name: Configure CMake
      working-directory: ${{runner.workspace}}
      run: |
          cmake -G "Visual Studio 17 2022" -A Win32 -S ExtIO_RTL -B build_ExtIO_RTL

    - name: Build
      working-directory: ${{runner.workspace}}
      shell: bash
      run: cmake --build build_ExtIO_RTL --config $BUILD_TYPE --target ExtIO_RTL

    #- name: Dir Listing
    #  working-directory: ${{runner.workspace}}
    #  shell: bash
    #  run: find . >src_listing.txt

    - name: Collect files to distribute
      working-directory: ${{runner.workspace}}
      shell: bash
      run: |
        cp "${{runner.workspace}}/ExtIO_RTL/README.md" ./
        cp "${{runner.workspace}}/ExtIO_RTL/COPYING" ./LICENSE
        cp "${{runner.workspace}}/build_ExtIO_RTL/Release/ExtIO_RTL.dll" ./

    - name: package and upload
      uses: actions/upload-artifact@v4
      with:
        name: extio_rtl
        path: |
            ${{runner.workspace}}/ExtIO_RTL.dll
            ${{runner.workspace}}/README.md
            ${{runner.workspace}}/LICENSE
