
name: Release Asset

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

permissions:
  contents: write


jobs:

  release_job:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create Release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create "${{ github.ref_name }}" \
          --repo "${{ github.repository }}" \
          --title "Release ${{ github.ref_name }}" \
          --notes "Precompiled ExtIO-DLL with README for Winrad/HDSDR"


  build-on-windows:
    needs: [release_job]
    runs-on: windows-2022

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
        submodules:  recursive

    - name: Configure CMake
      working-directory: ${{runner.workspace}}
      run: |
          cmake -G "Visual Studio 17 2022" -A Win32 -S ExtIO_RTL -B build_ExtIO_RTLw32
          cmake -G "Visual Studio 17 2022" -A x64   -S ExtIO_RTL -B build_ExtIO_RTLx64

    - name: Build ExtIO
      working-directory: ${{runner.workspace}}
      shell: bash
      run: cmake --build build_ExtIO_RTLw32 --config $BUILD_TYPE --target ExtIO_RTL

    - name: Collect ExtIO files to distribute and create ZIP
      working-directory: ${{runner.workspace}}
      shell: bash
      run: |
        cp "${{runner.workspace}}/ExtIO_RTL/README.md" ./
        cp "${{runner.workspace}}/ExtIO_RTL/COPYING" ./LICENSE
        cp "${{runner.workspace}}/build_ExtIO_RTLw32/Release/ExtIO_RTL.dll" ./
        7z a ExtIO_RTL_x32_${{ github.ref_name }}.zip README.md LICENSE ExtIO_RTL.dll

    - name: Release ExtIO Asset
      working-directory: ${{runner.workspace}}
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload "${{ github.ref_name }}" \
          --repo "${{ github.repository }}" \
          "ExtIO_RTL_x32_${{ github.ref_name }}.zip"

    - name: Build RTLSDR Tools for Windows
      working-directory: ${{runner.workspace}}
      shell: bash
      run: |
        cmake --build build_ExtIO_RTLw32 --config $BUILD_TYPE --target rtl_tools
        cmake --build build_ExtIO_RTLx64 --config $BUILD_TYPE --target rtl_tools

    - name: Collect tool files to distribute and create ZIP
      working-directory: ${{runner.workspace}}
      shell: bash
      run: |
        mkdir rtlsdr_tools_w32
        mkdir rtlsdr_tools_x64
        cp build_ExtIO_RTLw32/librtlsdr/src/Release/rtl_*.exe rtlsdr_tools_w32/
        cp build_ExtIO_RTLx64/librtlsdr/src/Release/rtl_*.exe rtlsdr_tools_x64/
        cp ExtIO_RTL/librtlsdr/README.md ./
        cp ExtIO_RTL/librtlsdr/README_improvements.md ./
        cp ExtIO_RTL/librtlsdr/README.rtlfm_cmdfile ./
        ls -lR >files.txt
        7z a rtlsdr_tools_${{ github.ref_name }}.zip rtlsdr_tools_w32 rtlsdr_tools_x64 files.txt README.md README_improvements.md README.rtlfm_cmdfile

    - name: Release rtlsdr tools Asset
      working-directory: ${{runner.workspace}}
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload "${{ github.ref_name }}" \
          --repo "${{ github.repository }}" \
          "rtlsdr_tools_${{ github.ref_name }}.zip"
